apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
  namespace: devops-ai
  labels:
    app: ai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-app
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HUGGINGFACE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: hf_api_token
            - name: HUGGINGFACE_API_URL
              value: "https://api-inference.huggingface.co/models/facebook/bart-large-cnn"
            - name: EXTERNAL_API_TIMEOUT
              value: "20"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
