apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
  namespace: devops-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-app
          image: 321858344734.dkr.ecr.us-west-2.amazonaws.com/devops-ai-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: TEXT_API_URL
              value: "http://text-processing.com/api/sentiment/"
            - name: EXTERNAL_API_TIMEOUT
              value: "10"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
