apiVersion: v1
kind: Service
metadata:
  name: ai-app-svc
  namespace: devops-ai
  labels:
    app: ai-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ai-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
