apiVersion: v1
kind: Service
metadata:
  name: ai-app-svc
  namespace: devops-ai
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: ai-app

