name: Build and Deploy AI App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 321858344734.dkr.ecr.us-west-2.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t devops-ai-app:latest .

      - name: Tag and Push to ECR
        run: |
          docker tag devops-ai-app:latest 321858344734.dkr.ecr.us-west-2.amazonaws.com/devops-ai-app:latest
          docker push 321858344734.dkr.ecr.us-west-2.amazonaws.com/devops-ai-app:latest

      - name: Update Kubernetes
        run: |
          aws eks update-kubeconfig --name main-cluster --region us-west-2
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/hpa.yaml
          kubectl rollout status deployment/ai-app -n devops-ai
